version: "3.3"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"
    
  backend:
    container_name: backend
    # build: ./backend
    # image: sumitramchandra/wanderlust_backend
    image: ${{ secrets.DOCKER_HUB_USERNAME }}/wanderlust_backend:${IMAGE_TAG}
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    # image: sumitramchandra/wanderlust_frontend
    # build: ./frontend
    image: ${{ secrets.DOCKER_HUB_USERNAME }}/wanderlust_frontend:${IMAGE_TAG}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env.sample
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  logs:
