on:
  push:
    branches:
      - saurabh
  pull_request:
    branches:
      - saurabh
jobs:
  zap_scan:
    runs-on: label-1
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        run: sudo bash /mnt/sec_tools/ZAP_2.15.0/zap.sh -cmd -quickurl http://34.229.46.124:5173 -quickout /mnt/sec_tools/ZAP_2.15.0/report.xml
      - name: copy report to runner work space
        run: cp /mnt/sec_tools/ZAP_2.15.0/report.xml /mnt/actions-runner/_work/zap-report
      - name: Upload Test results 
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/zap-report/report.xml
        
        # uses: zaproxy/action-full-scan@v0.10.0
        # with:
        #   #token: ${{ secrets.GITHUB_TOKEN }}
        #   docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        #   target: 'https://www.zaproxy.org/'
        #   rules_file_name: '.zap/rules.tsv'
        #   cmd_options: '-a'
