on:
  push:
    branches:
      - saurabh
  pull_request:
    branches:
      - saurabh
jobs:
   secret_scanning_repo:
      runs-on: label-1 
      steps:
      - name: Checkout repository
        #working-directory: mnt/actions-runner/_work/wander/wanderlust
        run: cd /mnt/actions-runner/_work/wander/wanderlust && pwd && sudo git pull https://github.com/Sb-fine/wanderlust.git 
      - name: secret_scanning_repo
        run: docker run  --rm --name=deepfence-secretscanner -v /var/run/docker.sock:/var/run/docker.sock quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0 --local string /mnt/actions-runner/_work/wander/wanderlust --output json > /mnt/actions-runner/_work/wander/deepfence_report/deepfence_repo.json
      - name: Upload results of secret scanning for repo
        uses: actions/upload-artifact@master
        with:
         path: /mnt/actions-runner/_work/wander/deepfence_report/deepfence_repo.json 
   # secret_scanning_container:
   #    runs-on: label-2 
   #    steps:
   #    - name: frontend_container_secret_scanning
   #      run:  docker run  --rm --name=deepfence-secretscanner -v /var/run/docker.sock:/var/run/docker.sock quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0 --image-name ${{ secrets.DOCKER_HUB_USERNAME }}/wanderlust_frontend:${{ env.TAG }} --output json > /tmp/node-secret-scan.json
   #    - name: backend_container_secret_scanning
   #      run: docker run  --rm --name=deepfence-secretscanner -v /var/run/docker.sock:/var/run/docker.sock quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0 --image-name ${{ secrets.DOCKER_HUB_USERNAME }}/wanderlust_backend:${{ env.TAG }} --output json > /tmp/node-secret-scan.json

   
       
