on:
  push:
    branches:
      - saurabh
  pull_request:
    branches:
      - saurabh
jobs:
   secret_scanning:
      runs-on: label-1 
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: secret_scanning_repo
        run: docker run -it --rm --name=deepfence-secretscanner \
             -v /mnt/actions-runner/_work/wanderlust/wanderlust:/deepfence/mnt \
             quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0 \
             && pwd    
    #--host-mount-path /deepfence/mnt --local /deepfence/mnt 
       
