on:
  push:
    branches:
      - saurabh
  pull_request:
    branches:
      - saurabh
jobs:
   secret_scanning:
      runs-on: label-1 
      steps:
      - name: Checkout repository
        #working-directory: mnt/actions-runner/_work/wander/wanderlust
        run: git clone https://github.com/Sb-fine/wanderlust.git && pwd
      - name: secret_scanning_repo
        run: docker run -it --rm --name=deepfence-secretscanner -v /var/run/docker.sock:/var/run/docker.sock quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0 --local string /mnt/actions-runner/_work/wander/wanderlust
   
    #--host-mount-path /deepfence/mnt --local /deepfence/mnt 
       
