on:
  push:
    branches:
      - saurabh
  pull_request:
    branches:
      - saurabh
jobs:
   secret_scanning_repo:
      runs-on: label-1 
      steps:
      - name: Checkout repository
        #working-directory: mnt/actions-runner/_work/wander/wanderlust
        run: cd /mnt/actions-runner/_work/wander/wanderlust && pwd && sudo git pull https://github.com/Sb-fine/wanderlust.git 
      - name: secret_scanning_repo
        run: docker run  --rm --name=deepfence-secretscanner -v /var/run/docker.sock:/var/run/docker.sock quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0 --local string /mnt/actions-runner/_work/wander/wanderlust --output json > /mnt/actions-runner/_work/wander/deepfence_report/deepfence_repo.json
      - name: Upload results of secret scanning for repo
        uses: actions/upload-artifact@master
        with:
         name: secret_scanning_repo_report
         path: /mnt/actions-runner/_work/wander/deepfence_report/deepfence_repo.json 
   secret_scanning_container:
      runs-on: label-2 
      steps:
      #for frontend
      - name: frontend_container_secret_scanning
        run:  docker run  --rm --name=deepfence-secretscanner -v /var/run/docker.sock:/var/run/docker.sock quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0 --image-name ${{ secrets.DOCKER_HUB_USERNAME }}/wanderlust_frontend:${{ env.TAG }} --output json > /home/ubuntu/actions-runner/_work/deepfence_report/frontend_deepfence.json
      - name: Upload results of secret scanning for frontend
        uses: actions/upload-artifact@master
        with:
         name: secret_scanning_frontend_report
         path: /home/ubuntu/actions-runner/_work/deepfence_report/frontend_deepfence.json
       #for backend
      - name: backend_container_secret_scanning
        run: docker run  --rm --name=deepfence-secretscanner -v /var/run/docker.sock:/var/run/docker.sock quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0 --image-name ${{ secrets.DOCKER_HUB_USERNAME }}/wanderlust_backend:${{ env.TAG }} --output json > /home/ubuntu/actions-runner/_work/deepfence_report/backend_deepfence.json
      - name: Upload results of secret scanning for backend
        uses: actions/upload-artifact@master
        with:
         name: secret_scanning_backend_report
         path: /home/ubuntu/actions-runner/_work/deepfence_report/backend_deepfence.json

   
       
