on:
  push:
    branches:
      - saurabh
  pull_request:
    branches:
      - saurabh
jobs:
  semgrep:
    runs-on: label-1
    steps:
      - uses: actions/checkout@v3
      - name: semgrep SAST
      - using: 'node20'
        run: cd /mnt/project/wanderlust
             semgrep ci
