on:
  push:
    branches:
      - saurabh
  pull_request:
    branches:
      - saurabh
jobs:
  depchecktest:
    runs-on: label-2
    name: image scanning
    steps:
  
      - name: frontend
        run: trivy image sumitramchandra/wanderlust_frontend --output /mnt/report/trivyreportfront.txt
      - name: copying report to runner workspace  
        run: sudo cp /mnt/report/trivyreportfront.txt /home/ubuntu/actions-runner/_work/trivy-report

      - name: backend
        run: trivy image sumitramchandra/wanderlust_backend --output /mnt/report/trivyreportbackend.txt
      - name: copying report to runner workspace  
        run: sudo cp /mnt/report/trivyreportbackend.txt /home/ubuntu/actions-runner/_work/trivy-report
                   
      - name: Upload Test results-1
        uses: actions/upload-artifact@master
        with:
           name: image frontend report
           path: /home/ubuntu/actions-runner/_work/trivy-report/trivyreportfront.txt
      - name: Upload Test results-2
        uses: actions/upload-artifact@master
        with:
           name: imagebackend report
           path: /home/ubuntu/actions-runner/_work/trivy-report/trivyreportbackend.txt
           
      
