on:
  push:
    branches:
      - saurabh
  pull_request:
    branches:
      - saurabh
jobs:
  depchecktest:
    runs-on: label-1
    name: image scanning
    steps:
  
      - name: frontend
        run: trivy image sumitramchandra/wanderlust_frontend --output /mnt/report/trivyreportfront.txt
      - name: copying report to runner workspace  
        run:  cp /mnt/report/trivyreportfront.txt /mnt/actions-runner/_work/trivy-report

      - name: backend
        run: trivy image sumitramchandra/wanderlust_backend --output /mnt/report/trivyreportbackend.txt
      - name: copying report to runner workspace  
        run: cp /mnt/report/trivyreportfront.txt /mnt/actions-runner/_work/trivy-report
                   
      - name: Upload Test results-1
        uses: actions/upload-artifact@master
        with:
           name: frontend report
           path: ${{github.workspace}}/trivy-report/trivyreportfront.txt
      - name: Upload Test results-2
        uses: actions/upload-artifact@master
        with:
           name: backend report
           path: ${{github.workspace}}/trivy-report/trivyreportfront.txt
           
      
